### ISSUE TITLE
Структура репозитория

### ISSUE THREAD

**Issue by akuznetsov-md** [sanyamaks/test_task_login_react#1]
Если не рассматривать моно-репозиторий для нескольких проектов, то не имеет смысла вкладывать файлы проекта в дополнительную папку `my-app`.

Также не стоит хранить в репозитории файлы, специфичные для IDE — `.idea`, `.vscode` и т.д. Единые правила форматирования и стилизации достигаются при помощи таких инструментов как `eslint` и `prettier`, а все остальные настройки могут быть индивидуальными.

**Comment by sanyamaks** [comment]
Изначально create-reacte-app ругался на слишком длинное название директории, поэтому создал папку в папке. Сейчас же все заработало - магия. Исправлено.
.idea удалил. Исправлено.
Eslint и prettier установлены, остальное установлено для личного удобства. Замечания не понял насчет индивидуальности. Их пока удалить, чтобы не путаться?

**Comment by akuznetsov-md** [comment]
Про индивидуальные настройки — это не замечание, просто комментарий по поводу хранения файлов IDE. IDE у всех могут быть разными с разными набором плагинов: кому как удобнее.
