### ISSUE TITLE
Именование файлов компонентов

### ISSUE THREAD

**Issue by akuznetsov-md** [sanyamaks/test_task_login_react#2]
Не стоит в названии компонента использовать слово component. В философии реакта всё есть компонент.

Кастомные компоненты в реакте (т.е. все компоненты, кроме стандартных html-ских) должны называться с большой буквы. 
В своих проектах я стараюсь именовать папки с файлами компонента также как и сам компонент (с сохранением регистра).
Т.е. в моем проекте была бы структура
```
src/components/Button/Button.js
src/components/Button/Button.css
src/screens/Login/Login.js
src/screens/Login/Login.css
```
и т.д.

- Это освобождает от необходимости придумывать дополнительные названия для компонента.
- Это простое правило именование, которым могут легко следовать все члены команды

Использовать суффикс .style для файлов со стилями имеет смысл в случае использования CSS-in-JS решений. Если же это обычные css файлы, то суффикс можно не указывать. Мы понимаем что это стили по расширению файла.

**Comment by sanyamaks** [comment]
Доклад на meet up  по Angular сбил с толку. Исправлено.

**Comment by akuznetsov-md** [comment]
Скинь ссылку, пожалуйста.

**Comment by sanyamaks** [comment]
https://vk.io/aAJQ7
Говорилось о том, что удобно добавлять .component в названии файла. Якобы удобнее при поиске.
Сравнивать react и angular не могу, но мне показалось это удобным

**Comment by akuznetsov-md** [comment]
Подход, описанный в презентации, вполне имеет смысл. 

Мне тоже нравится использование суффиксов для удобного поиска какой-то части компонента. Но слово component я опускаю:
```
SomeComponent/
  SomeComponent.js
  SomeComponent.i18n.js
  SomeComponent.test.js
```
и т.д.
