### ISSUE TITLE
Переиспользуемые (общие, базовые, shared) компоненты не должны содержать контекст их использования

### ISSUE THREAD

**Issue by akuznetsov-md** [sanyamaks/test_task_login_react#3]
```
import React, { PureComponent } from "react";
import "./button.style.css"

class Button extends PureComponent {
  render() {
    if (this.props.isActive) {
      return (
        <input
          type="submit"
          className="form__button form__button_login"
          value="Login"
          onClick={this.props.onClick}
          onSubmit={this.props.onClick}
        />
      );
    } else if (!this.props.isActive) {
      return (
        <input
          type="button"
          className="form__button form__button_logout"
          value="Logout"
          onClick={this.props.onClick}
        />
      );
    }
  }
}

export default Button;
```

Проблема такого подхода к декомпозиции в том, что это компонент нельзя переиспользовать. У компонента кнопки только два варианта — либо это кнопка логина, либо это кнопка логаута.

Как бы ты изменил этот компонент, чтобы была возможность добавить кнопку в произвольное место приложения?

**Comment by akuznetsov-md** [comment]
Рассматривай создание собственных компонентов как создание кастомных html тегов. Кастомный `<Button>` этот тот же `<button>` только стилизованный.

**Comment by sanyamaks** [comment]
> Как бы ты изменил этот компонент, чтобы была возможность добавить кнопку в произвольное место приложения?
Попробовал исправить.

**Comment by sanyamaks** [comment]
> Рассматривай создание собственных компонентов как создание кастомных html тегов. Кастомный `<Button>` этот тот же `<button>` только стилизованный.
Не смог уловить мысль.

**Comment by akuznetsov-md** [comment]
> > Как бы ты изменил этот компонент, чтобы была возможность добавить кнопку в произвольное место приложения?
> Попробовал исправить.

Я бы хотел, чтобы перед работой с кодом ты описал суть исправления. Иначе не понятно, ты случайно сделал так или это результат определенного хода мыслей.

**Comment by akuznetsov-md** [comment]
> > Рассматривай создание собственных компонентов как создание кастомных html тегов. Кастомный `<Button>` этот тот же `<button>` только стилизованный.

> Не смог уловить мысль.

Основная мысль в том, чтобы не вносить дополнительной когнитивной нагрузки в твой код, создавая кастомные свойства там, где можно обойтись стандартными.

В первом варианте компонент Button был даже не совсем компонентом :) Это просто часть кода, которая была выделена в отдельный файл.

Во втором варианте стало лучше, но осталось свойство modificator. Не понятно, что туда передавать и как именно может измениться кнопка. Этого свойства нет в спецификации HTML, нет в документации компонента и из его названия явно не понятно, что оно делает.

Подумай, как еще можно улучшить компонент Button, исходя из комментариев выше.

**Comment by sanyamaks** [comment]
let buttonClassName = "button";
    if (this.props.value === "Login") {
      buttonClassName += " button_login";
    } else if (this.props.value === "Logout"){
      buttonClassName += " button_logout";
    }
Вижу только такой вариант решения.
То есть при появлении необходимости новой кнопки, добавлять новый стиль.
Если бы была необходимость переиспользовать много раз компонент, то, наверное, пришлось как-то группировать в разные группы все варианты.
Думал как избавить вообще от изменения стиля, но не нашел способа, поскольку согласно макету слишком много изменений происходит при разных ситуациях.

**Comment by akuznetsov-md** [comment]
`button_login` и `button_logout` — это некоторые стили, которые задаются исходя из контекста использования, т.е. где-то _снаружи_ компонента. Так пусть эти стили и назначаются _снаружи_, а не внутри компонента.

Свойство `value` тоже зависит от контекста и тоже должно задаваться снаружи — и у тебя это уже сделано.

**Comment by sanyamaks** [comment]
Непонятен момент с местом хранения стилей элемента `user-page__button` и  `form-login__button`. С одной стороны все это относится к компоненту `Button`, и должны храниться в Button.css . Но с другой, что мне кажется более логичным - они все-таки являются элементами блоков `user-page` и `form-login` и должны хранитьтся рядом с компонентами `UserPage` и `Login`.

**Comment by akuznetsov-md** [comment]
> Непонятен момент с местом хранения стилей элемента user-page__button и form-login__button.

Это правильный вопрос. 

> мне кажется более логичным - они все-таки являются элементами блоков user-page и form-login и должны хранитьтся рядом с компонентами UserPage и Login.

А это ответ на него :)

**Comment by akuznetsov-md** [comment]
В предыдущем комменте я скидывал ссылку на секцию "Микс" в документации БЭМ. Это как раз про это. Отдельный DOM-узел (кнопка) может быть одновременно и блоком и элементом другого блока.
