### ISSUE TITLE
Зоны отвественности компонентов

### ISSUE THREAD

**Issue by akuznetsov-md** [sanyamaks/test_task_login_react#4]
По какой причине ты решил хранить введенные email и пароль в стейте компонента App? В реальных проектах такой подход приведет к разрастанию компонента, который невозможно будет поддерживать.

Попробуй перенести функционал, который нужен только работы с формой в компонент Login, функционал для работы с профилем пользователя — в соответствующий ему компонент. 

И поработай над неймингом компонента с профилем пользователя. Название `logout` не соответствует содержимому.

**Comment by sanyamaks** [comment]
В одном из видео курсов читал, что функционал должен работать с головы. И сам пример был поднятия всех функций и состояний до App.js. 
Также я понимаю, что компонентам не нужно знать о том, что происходит внутри других компонентов. 
Однако, из-за малого опыта не всегда получается понять, что стоит поднимать, а что нет.
Исправлено.
Logout переименован в UserPage.

**Comment by akuznetsov-md** [comment]
>В одном из видео курсов читал, что функционал должен работать с головы. И сам пример был поднятия всех функций и состояний до App.js

Для каждой best practice должно быть какое-то обоснование. Я не вижу логике в переносе ВСЕХ функций и состояний в корневой компонент.

>Однако, из-за малого опыта не всегда получается понять, что стоит поднимать, а что нет.

Структура веб приложения — древовидная. Компонент знает свое содержимое, но не знает, куда вложен сам. Чтобы передать данные из одной ветки в другую, можно найти для них общего родителя и поднять хранение состояния до этого уровня.

Таким образом мы не будем загромождать корневой компонент, а распределим хранение состояния по другим узлам. Это немного улучшит ситуацию, но все равно это не лучшее решение.

Как думаешь, какие недостатки у такого подхода?

**Comment by sanyamaks** [comment]
Могу предположить, что мы нагружаем дополнительный (родительский) компонент при этом. Возможно, влияет на производительность. Чем сложнее многоэтажнее приложение, тем дольше передача данных от одного дочернего элемента к другому.
Если бы данные передавали напрямую от одного компонента к другому, то это бы ускорило процесс.

**Comment by akuznetsov-md** [comment]
> Могу предположить, что мы нагружаем дополнительный (родительский) компонент при этом

Для твоего изначального подхода — да, слишком много всего будет нагромождено в одном компоненте. В варианте, когда мы поднимаем стейт до первого общего родителя этого уже меньше.

> Возможно, влияет на производительность. Чем сложнее многоэтажнее приложение, тем дольше передача данных от одного дочернего элемента к другому.

Сложно однозначно сказать, что упадет производительность. Но в варианте, когда мы поднимаем стейт до первого общего родителя лишних рендеров будет меньше, т.к. будет затрагиваться только часть дерева компонентов. 

> Если бы данные передавали напрямую от одного компонента к другому, то это бы ускорило процесс.

А вот это уже ближе к правде. Когда мы передаем данные от одного компонента другому всегда может быть N-е количество промежуточных компонентов, которые просто ретранслируют свойства сверху вниз. Это приводит к лишним вызовам рендера этих компонентов. Чтобы оптимизировать этот процесс, можно воспользоваться услугами некоторой третьей стороны. В реакте для этого используют контекст https://learn-reactjs.ru/core/context

**Comment by sanyamaks** [comment]
Прочитал.
Насколько уместно был бы использован контекст здесь? Как я понимаю, в данном случае количество шагов одинаково?
Для практики стоит вставить? Или в рамках этого задания оставить как есть?

**Comment by akuznetsov-md** [comment]
В рамках этого задания использовать контекст не имеет смысла. В ветке `#4` пересмотри набор свойств, который ты пробрасываешь из App в дочерние компоненты — там есть лишние.

**Comment by sanyamaks** [comment]
Не сразу сообразил, что данные name и photoUrl передаются внутри функции, и что изменение состояния происходит именно только в App.js, а не еще и в Login.js.
