### ISSUE TITLE
Поле ввода следует вынести в отдельный компонент

### ISSUE THREAD

**Issue by akuznetsov-md** [sanyamaks/test_task_login_react#9]
Поле ввода в терминологии БЭМ это все-таки не элемент формы авторизации, а самостоятельный блок, который может быть переиспользован. Блок в БЭМе = компонент в реакте.

**Comment by sanyamaks** [comment]
Исправил, посмотри, пожалуйста:
https://github.com/sanyamaks/test_task_login_react/pull/10
Так и не сообразил, что не так со стандартным `pattern` у `input`. В коде проверка по шаблону работает на ура. Обводка красным `input` происходит явно не тогда, когда нужно, а вернее всегда.

**Comment by akuznetsov-md** [comment]
> Так и не сообразил, что не так со стандартным pattern у input

Скорее всего это проблема реакта. Если проверить на чистом html, атрибут отрабатывает нормально.
